services:
  - type: web
    name: fogon
    runtime: docker
    plan: free
    envVars:
      - key: DB_HOST
        value: sql10.freesqldatabase.com
      - key: DB_USER
        value: sql10829093
      - key: DB_PASSWORD
        value: sBciLrbrmk
      - key: DB_NAME
        value: sql10829093
      - key: DB_PORT
        value: "3306"